languageCode                 = "na"
defaultContentLanguage = "na"
baseURL                          = "https://hayami.blog/"
enableRobotsTXT            = true
[params]
publisher = "hayami.blog"
ogimage  = "logo.svg"

[Languages]

[Languages.na]
title = "hayami.blog"

[Languages.ja]
title = "hayami.blog"

[Languages.en]
title = "hayami.blog"
